language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
env:
  - R_MAX_NUM_DLLS=250
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
      - libreadline-dev
before_install:
  - "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test"
  - "sudo add-apt-repository -y ppa:marutter/c2d4u"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y r-cran-rcpp r-bioc-rhdf5 r-cran-caret r-cran-mclust r-cran-ggridges r-cran-dplyr r-cran-purrr r-cran-igraph r-bioc-s4vectors r-cran-xml2 r-cran-rcurl r-cran-data.table r-cran-xml r-cran-httpuv r-cran-rcppeigen r-cran-vgam r-cran-jsonlite r-cran-git2r r-cran-hms r-cran-matrixstats"
install:
 - R -e 'install.packages("devtools")'
 - R -e 'setRepositories(ind = 1:2)'
 - R -e 'devtools::install(upgrade_dependencies=F)'
r_check_args: "--no-tests --no-manual --no-vignettes --no-build-vignettes"
r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'covr::codecov(function_exclusions = c("sample_snapshot", "snapshot_sampler", "sample_synchronised", "synchronised_sampler"))'
