language: r
sudo: required
dist: trusty
bioc_required: true
warnings_are_errors: true
cache: packages
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
      - libreadline-dev
install:
 - R -e 'install.packages("remotes")'
 - R -e 'remotes::install_deps(dependencies = T, upgrade = T)'
 - R -e 'remotes::install_local(".")'
