language: r
sudo: required
dist: trusty
bioc_required: true
warnings_are_errors: true
cache: packages
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
      - libreadline-dev
install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_github("r-lib/callr")'
  - R -e 'devtools::install_github("dynverse/devtools")'
  - R -e 'devtools::install(dependencies = TRUE, upgrade_dependencies = TRUE)'
