language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
env:
  - R_MAX_NUM_DLLS=250
r_binary_packages:
  - rhdf5
  - caret
  - mclust
  - ggridges
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
      - libreadline-dev
install:
 - R -e 'install.packages("devtools")'
 - R -e 'setRepositories(ind = 1:2)'
 - R -e 'devtools::install(dependencies = NA, upgrade = T, threads=2)'
r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'covr::codecov(function_exclusions = c("sample_snapshot", "snapshot_sampler", "sample_synchronised", "synchronised_sampler"))'
